config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "static_pages#about"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get "static_pages/top"
  get "static_pages/about"
  get "static_pages/terms"
  get "static_pages/privacy_policy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :techniques, only: %i[index] do
    get "autocomplete", on: :collection
    get "search", on: :collection
    get "favorites", on: :member
  end
  namespace :techniques do
    resources :youtube, only: %i[new create show edit update destroy]
    resources :twitter, only: %i[new create show edit update destroy]
  end
  resources :favorites, only: %i[create destroy]
  resources :folders, only: %i[new create show edit update destroy]
  resources :categories, only: %i[index show] do
    member do
      post "follow", to: "follows#create"
      delete "unfollow", to: "follows#destroy"
    end
  end
  get "/youtube/title", to: "youtube_api#title"
end

app/models/technique.rb
class Technique < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :source_type, presence: true
  validates :source_url, presence: true

  belongs_to :user

  enum source_type: { youtube: 1, twitter: 2 }

  has_many :favorites, dependent: :destroy
  has_many :technique_categories, dependent: :destroy
  has_many :categories, through: :technique_categories

  attr_accessor :category_names

  # お気に入り順にソートする
  scope :most_favorites, -> {
    left_joins(:favorites).group(:id).order("count(favorites.id) desc")
  }

  after_save :assign_categories

  after_create_commit :send_notifications_for_followers

  YOUTUBE_ID_REGEX = %r{(?:https://www\.youtube\.com(?:/embed/|/watch\?v=)|https://youtu\.be/)([a-zA-Z0-9_-]{11})}

  def youtube_video_id
    return nil unless youtube? && source_url.present?

    match = source_url.match(YOUTUBE_ID_REGEX)

    match[1] if match
  end

  def x_to_twitter_change_url
    return unless twitter? && source_url.match?(/\Ahttps:\/\/x\.com\//)
    source_url.sub("x.com", "twitter.com")
  end

  def calculate_video_timestamp
    if source_type == "youtube"
      time = video_timestamp.split(":").map(&:to_i)

      case time.length
      when 3
        time[0]*3600 + time[1]*60 + time[2]
      when 2
        time[0]*60 + time[1]
      when 1
        time[0]
      else
        0
      end
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "title" ]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  private

  def assign_categories
    return if category_names.blank?

    old_categories = categories.to_a

    new_categories = category_names.split(",").map do |name|
      Category.find_or_create_by(name: name.strip)
    end

    self.categories = new_categories
    removed_categories = old_categories - new_categories

    removed_categories.each do |category|
      if category.reload.technique_categories.empty?
        category.destroy
      end
    end
  end

  def send_notifications_for_followers
    if categories.any?
      categories.each do |category|
        category.followers.where.not(id: user_id).each do |follower|
          notification = Notification.create!(
            user: follower,
            notifiable: self,
            message: "#{category.name}に新しいテクニック「#{title}」が投稿されました。"
          )
          NotificationMailer.new_technique_notification(follower, self, category).deliver_later
        end
      end
    else
      Rails.logger.warn "Warning: Technique ##{id} has no categories associated after commit. No notifications will be sent."
    end
  end
end

app/controllers/techniques/twitter_controller.rb
class Techniques::TwitterController < ApplicationController
  before_action :authenticate_user!, except: [ :show ]

  def new
    @technique = Technique.new(source_type: "twitter")
  end

  def create
    @technique = current_user.techniques.build(technique_params)
    @technique.source_type = "twitter"
    category_names = params[:technique][:category_names]

    if @technique.save
      if category_names.present?
        categories = category_names.split(",").map(&:strip).uniq
        create_or_update_technique_categories(@technique, categories)
      end
      redirect_to techniques_twitter_path(@technique), success: t("defaults.flash_message.created", item: "Xの#{Technique.model_name.human}")
    else
      flash.now[:error] = t("defaults.flash_message.not_created", item: Technique.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @technique = Technique.find(params[:id])
    recommend_id = Technique.where(source_type: "twitter").where.not(id: @technique.id).pluck(:id).sample(2)
    @recommend_techniques = Technique.where(id: recommend_id)
  end

  def edit
    @technique = current_user.techniques.find(params[:id])
  end

  def update
    @technique = current_user.techniques.find(params[:id])
    category_names = params[:technique][:category_names]

    if @technique.update(technique_params)
      if category_names.present?
        categories = params[:technique][:category_names].split(",").map(&:strip).uniq
        create_or_update_technique_categories(@technique, categories)
      end
      redirect_to techniques_twitter_path(@technique), success: t("defaults.flash_message.updated", item: Technique.model_name.human)
    else
      flash.now[:error] = t("defaults.flash_message.not_updated", item: Technique.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    technique = current_user.techniques.find(params[:id])
    technique.destroy!
    redirect_to techniques_path, success: t("defaults.flash_message.deleted", item: Technique.model_name.human), status: :see_other
  end

  private

  def technique_params
    params.require(:technique).permit(:title, :source_type, :source_url)
  end

  def create_or_update_technique_categories(technique, categories)
    technique.categories.destroy_all
    begin
      categories.each do |category|
        category = Category.find_or_create_by(name: category)
        technique.categories << category
      rescue ActiveRecord::RecordInvalid
        false
      end
    end
  end
end

app/controllers/techniques/youtube_controller.rb
class Techniques::YoutubeController < ApplicationController
  before_action :authenticate_user!, except: [ :show ]

  def new
    @technique = Technique.new(source_type: "youtube")
  end

  def create
    @technique = current_user.techniques.build(technique_params)
    @technique.source_type = "youtube"

    if @technique.save
      redirect_to techniques_youtube_path(@technique), success: t("defaults.flash_message.created", item: "Youtubeの#{Technique.model_name.human}")
    else
      flash.now[:error] = t("defaults.flash_message.not_created", item: Technique.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @technique = Technique.find(params[:id])

    # youtubeAPIを引っ張ってくる
    youtube_service = YoutubeService.new
    @movie_title = youtube_service.get_movie_title(@technique.youtube_video_id)

    # おすすめ動画のためにIDをランダムで引っ張ってくる
    recommend_id = Technique.where(source_type: "youtube").where.not(id: @technique.id).pluck(:id).sample(5)
    @recommend_techniques = Technique.where(id: recommend_id)
  end

  def edit
    @technique = current_user.techniques.find(params[:id])
    @technique.category_names = @technique.categories.pluck(:name).join(",")
  end

  def update
    @technique = current_user.techniques.find(params[:id])

    if @technique.update(technique_params)
      redirect_to techniques_youtube_path(@technique), success: t("defaults.flash_message.updated", item: Technique.model_name.human)
    else
      flash.now[:error] = t("defaults.flash_message.not_updated", item: Technique.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    technique = current_user.techniques.find(params[:id])
    technique.destroy!
    redirect_to techniques_path, success: t("defaults.flash_message.deleted", item: Technique.model_name.human), status: :see_other
  end

  private

  def technique_params
    params.require(:technique).permit(:title, :source_type, :source_url, :video_timestamp, :category_names)
  end
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  def index
    # まとめて記載
    most_favorites_techniques = Technique.most_favorites.includes(:categories)

    if params[:most_favorites]
      @techniques = most_favorites_techniques
    else
      @techniques = Technique.includes(:categories).order(created_at: :desc)
    end

    @swiper_youtube_techniques = most_favorites_techniques.where(source_type: "youtube").limit(5)

    @youtube_techniques = @techniques.where(source_type: "youtube").limit(6)
    @twitter_techniques = @techniques.where(source_type: "twitter").limit(6)

    @beginner_categories  = Category.beginner
    @agents_categories = Category.agents
    @maps_categories = Category.maps
    @others_categories = Category.others
  end

  def search
    @q = Technique.ransack(params[:q])
    @results = @q.result(distinct: true).includes(:categories)
  end

  def favorites
    @favorite_techniques = current_user.favorite_techniques.includes(:categories)
    @folders = current_user.folders.includes(:user)

    @folder = Folder.new
    @my_folders = current_user.folders.includes(:user)

    @followed_categories = current_user.following_categories.all
  end

  def autocomplete
    @techniques = Technique.where("title LIKE ?", "%#{params[:q]}%")

    respond_to do |format|
      format.html { render layout: false }
    end
  end

  private
  def folder_params
    params.require(:folder).permit(:title)
  end
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/views/techniques/_favorite_button.html.erb
<% if user_signed_in? %>
  <% if current_user.favorite?(technique) %>
    <%= link_to favorite_path(current_user.favorites.find_by(technique_id: technique.id)), data: { turbo_method: :delete }, class: "btn btn-dash btn-warning" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
          <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
        </svg>
        <span class="relative">お気に入り解除</span>
    <% end %>
  <% else %>
    <%= link_to favorites_path(technique_id: technique.id), data: { turbo_method: :post }, class: "btn btn-soft btn-warning" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
        <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.56.56 0 0 0-.163-.505L1.71 6.745l4.052-.576a.53.53 0 0 0 .393-.288L8 2.223l1.847 3.658a.53.53 0 0 0 .393.288l4.052.575-2.906 2.77a.56.56 0 0 0-.163.506l.694 3.957-3.686-1.894a.5.5 0 0 0-.461 0z"/>
      </svg>
      <span>お気に入り</span>
    <% end %>
  <% end %>
<% end %>

app/views/techniques/_twitter_technique.html.erb
<div class="relative mx-auto max-w-7xl">
  <% if @twitter_techniques.present? %>
    <div class="mx-auto mt-8 grid max-w-lg gap-12 lg:max-w-none lg:grid-cols-3">
      <% @twitter_techniques.each do |technique| %>
        <div class="mb-12 flex flex-col overflow-hidden">
          <%= link_to techniques_twitter_path(technique), data: { turbo_frame: "_top" } do %>

            <%# x %>
            <div class="shrink-0">
              <blockquote class="twitter-tweet">
                <a href="<%= technique.x_to_twitter_change_url || technique.source_url %>"></a>
              </blockquote>
              <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>

            <%# テキスト情報 %>
            <div class="flex flex-1 flex-col justify-between pt-6 pl-6 pr-6">
              <div class="flex-1">
                <div class="mt-2 mb-2">
                  <% technique.categories.each do |category| %>
                    <%= link_to category.name, category_path(category), data: { turbo_frame: "_top" }, class: "badge badge-info" %>
                  <% end %>
                </div>

                <div class="mt-3 block">
                  <h3 class="text-2xl font-semibold leading-none tracking-tighter mb-4">
                    <%= technique.title %>
                  </h3>
                </div>
              </div>

            </div>

            <div class="flex justify-center items-center gap-2 mt-2">
              <%= link_to "詳細画面へ", techniques_twitter_path(technique), data: { turbo_frame: "_top" }, class: "btn btn-primary" %>
              <div id="<%= dom_id(technique, :favorite_button) %>">
                <%= render "techniques/favorite_button", technique: technique %>
              </div>
            </div>

          <% end %>

        </div>
      <% end %>
    </div>

    <% else %>

      <div class="mt-6 flex justify-center">
        <div role="alert" class="alert alert-warning">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-6 w-6 shrink-0 stroke-current"
              fill="none"
              viewBox="0 0 24 24">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          <span>Xのテクニックは投稿されていません</span>
        </div>
      </div>

    <% end %>

  </div>
</div>

app/views/techniques/_youtube_technique.html.erb
<div class="relative mx-auto max-w-7xl">
  <% if @youtube_techniques.present? %>
    <div class="mx-auto mt-8 grid max-w-lg gap-12 lg:max-w-none lg:grid-cols-3">
      <% @youtube_techniques.each do |technique| %>
        <div class="mb-12 flex flex-col overflow-hidden">
          <%= link_to techniques_youtube_path(technique), data: { turbo_frame: "_top" } do %>

            <%# youtube %>
            <div class="shrink-0">
              <iframe class="w-full aspect-video"
                      src="https://www.youtube.com/embed/<%= technique.youtube_video_id %>?start=<%= technique.calculate_video_timestamp %>"
                      frameborder="0"
                      allowfullscreen>
              </iframe>
            </div>

            <%# テキスト情報 %>
            <div class="flex flex-1 flex-col justify-between pt-6 pl-6 pr-6">
              <div class="flex-1">
                <div class="flex text-sm">
                  <span>開始地点: <%= technique.video_timestamp %></span>
                </div>

                <div class="mt-2 mb-2">
                  <% technique.categories.each do |category| %>
                    <%= link_to category.name, category_path(category), data: { turbo_frame: "_top" }, class: "badge badge-info" %>
                  <% end %>
                </div>

                <div class="mt-3 block">
                  <h3 class="text-2xl font-semibold leading-none tracking-tighter mb-4">
                    <%= technique.title %>
                  </h3>
                  <%# p class="text-lg font-normal mb-4">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
                    facilis asperiores porro quaerat doloribus, eveniet dolore.
                    Adipisci tempora aut inventore optio animi., tempore
                    temporibus quo laudantium.
                  </p%>
                </div>
              </div>

            </div>

            <div class="flex justify-center items-center gap-2 mt-2">
              <%= link_to "詳細画面へ", techniques_youtube_path(technique), data: { turbo_frame: "_top" }, class: "btn btn-primary" %>
              <div id="<%= dom_id(technique, :favorite_button) %>">
                <%= render "techniques/favorite_button", technique: technique %>
              </div>
            </div>

          <% end %>

        </div>
      <% end %>
    </div>

  <% else %>

    <div class="mt-6 flex justify-center">
      <div role="alert" class="alert alert-warning">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6 shrink-0 stroke-current"
            fill="none"
            viewBox="0 0 24 24">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
        <span>YouTubeのテクニックは投稿されていません</span>
      </div>
    </div>

  <% end %>

  </div>
</div>

app/views/techniques/favorites.html.erb
<% content_for(:title, t(".title")) %>

<div class="text-center">
  <div class="text-5xl font-bold mt-8 ml-10">マイページ</div>
  <div class="text-xl font-semibold underline mt-4 ml-10">このページではお気に入りしたテクニックが確認できます</div>
</div>

<%
=begin%>

<div class="text-lg font-semibold text-center mt-4 mb-4">お気に入りフォルダ</div>
<% if @my_folders.present? %>
  <% @my_folders.each do |folder| %>
    <div class="btn">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-folder" viewBox="0 0 16 16">
        <path d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a2 2 0 0 1 .342-1.31zM2.19 4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139q.323-.119.684-.12h5.396z"/>
      </svg>
      <%= link_to folder.title, folder_path(folder) %>
    </div>
  <% end %>
<% else %>
  <div class="text-red-500">何もフォルダが作成されていません</div>
<% end %>

<!-- モーダル：新規フォルダ作成 -->
<button class="btn btn-primary" onclick="create_folder.showModal()">新規フォルダ作成</button>
<dialog id="create_folder" class="modal">
  <div class="modal-box">
    <form method="dialog">
      <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
    </form>
    <h3 class="text-lg font-bold">新規フォルダ作成</h3>
    <%= form_with model: @folder, url: folders_path do |f| %>
      <div class="field py-2 px-4">
        <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "input input-md input-bordered w-full", placeholder: "フォルダのタイトル" %>
      </div>

      <div class="actions text-center py-4 px-4">
        <%= f.submit "フォルダを作成する！", class: "btn" %>
      </div>
    <% end %>
  </div>
</dialog>

<%
=end%>

<%# フォロー中のカテゴリー表示 %>

<div class="text-center">
  <div class="text-2xl font-semibold m-8">フォロー中のカテゴリー</div>
  <div>
    <% if @followed_categories.present? %>
      <% @followed_categories.each do |category| %>
        <div class="flex justify-center items-center space-x-4 m-2">
          <%= link_to category.name, category_path(category), class: "text-blue-600 hover:underline" %>
          <%= button_to "フォロー解除", unfollow_category_path(category), method: :delete, data: { confirm: "本当にフォローを解除しますか?"}, class: "hidden h-8 w-32 rounded-full bg-red-500 font-extrabold text-white hover:bg-red-600 md:block" %>
        </div>
      <% end %>
    <% else %>
      <div>まだフォローしているカテゴリーはありません</div>
      <div><%= link_to "カテゴリー一覧を見る", categories_path %></div>
    <% end %>
  </div>
</div>

<%# お気に入りした投稿の一覧表示 %>

<section>
  <div class="container py-8 mx-auto">
    <div class="border-b border-gray-600 pb-4">
      <h3 class="text-xl text-center font-semibold leading-6">
        Movies
      </h3>
    </div>

  <% @youtube_techniques = @favorite_techniques.where(source_type: "youtube") %>
  <%= render "techniques/youtube_technique" %>
  </div>

  </div>
</section>

<section>
  <div class="container py-8 mx-auto">
    <div class="border-b border-gray-600 pb-4">
      <h3 class="text-xl text-center font-semibold leading-6">
        Posts
      </h3>
    </div>

  <% @twitter_techniques = @favorite_techniques.where(source_type: "twitter") %>
  <%= render "techniques/twitter_technique" %>
  </div>

  </div>
</section>

app/views/techniques/search.html.erb
<% content_for(:title, t(".title")) %>

<div class="text-5xl font-bold text-center m-10">検索</div>

<div class="text-center">
<%= search_form_for @q, html: { data: { turbo_frame: "search_result" } }, url: search_techniques_path, method: :get do |f| %>
  <div data-controller="autocomplete" data-autocomplete-url-value="<%= autocomplete_techniques_path %>" role="combobox" class="relative inline-block text-left w-1/3">
    <%= f.search_field :title_cont, class: "input input-md input-bordered w-full", placeholder: "タイトル・キャラクター・マップ名で検索", data: { autocomplete_target: 'input' } %>
    <%= f.hidden_field :title, data: { autocomplete_target: 'hidden' } %>
    <ul class="list-group bg-white absolute z-10 w-full border border-gray-200 rounded-md shadow-lg md:text-sm" data-autocomplete-target="results"></ul>
  </div>
    <%= f.submit '検索', class: "btn" %>
<% end %>
</div>

<%= turbo_frame_tag "search_result" do %>

  <div class="text-5xl font-bold text-center m-8 underline">検索結果</div>


<section>
  <div class="container py-8 mx-auto">
    <div class="border-b border-gray-600 pb-4">
      <h3 class="text-xl text-center font-semibold leading-6">
        Movies
      </h3>
    </div>

    <% @youtube_techniques = @results.where(source_type: "youtube") %>
    <%= render "techniques/youtube_technique" %>
  </div>

  </div>
</section>

<section>
  <div class="container py-8 mx-auto">
    <div class="border-b border-gray-600 pb-4">
      <h3 class="text-xl text-center font-semibold leading-6">
        Posts
      </h3>
    </div>

    <% @twitter_techniques = @results.where(source_type: "twitter") %>
    <%= render "techniques/twitter_technique" %>
  </div>

  </div>
</section>

<% end %>

app/views/techniques/show.html.erb
<% content_for(:title, t(".title")) %>
<div class="flex flex-col md:flex-row max-w-screen-2xl mx-auto px-4 py-6">
  <!-- メイン動画 -->
  <div class="w-full md:w-2/3 md:pr-6">
    <div class="w-full aspect-video bg-gray-800">
      <iframe class="w-full aspect-video"
              src="https://www.youtube.com/embed/<%= @technique.embed_id_from_youtube_url %>&amp;start=<%= @technique.calculate_video_timestamp %>"
              frameborder="0"
              allowfullscreen>
      </iframe>
    </div>
    <div class="mt-4 text-xl font-bold"><%= @technique.title%></div>
    <div class="mt-4 text-md font-bold">チャンネルのタイトル</div>


          <% if current_user.own?(@technique) %>
            <%= link_to edit_technique_path(@technique), id: "button-edit-#{@technique.id}" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
              </svg>
            <% end %>
            <%= link_to technique_path(@technique), id: "button-destroy-#{@technique.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') }  do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
              </svg>
            <% end %>
          <% end %>

    <div class="mt-2 flex space-x-3">
      <a href="https://www.youtube.com/watch?v=<%= @technique.only_id_from_youtube_url %>" class="btn px-4 py-2 bg-red-500 text-white" target="_blank" rel="noopener noreferrer">YouTubeへ</a>
      <button class="px-4 py-2 bg-gray-300 text-black rounded-lg">Xでシェア</button>
    </div>
    <div class="px-6 pt-2 pb-2">
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= @technique.character %></span>
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= @technique.map %></span>
    </div>
  </div>

  <!-- おすすめ動画 -->
  <div class="w-full md:w-1/3 mt-6 md:mt-0">
    <h2 class="text-lg font-semibold mb-4">おすすめ動画</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-1 gap-4">

      <div class="flex space-x-3">
        <img class="w-32 h-18 object-cover rounded-lg bg-gray-300" src="https://img.youtube.com/vi/<%= @technique.only_id_from_youtube_url %>/maxresdefault.jpg">
        <div class="flex-1">
          <p class="text-sm font-medium">おすすめ動画のタイトル1</p>
        </div>
      </div>

      <div class="flex space-x-3">
        <img class="w-32 h-18 object-cover rounded-lg bg-gray-300" src="https://img.youtube.com/vi/<%= @technique.only_id_from_youtube_url %>/maxresdefault.jpg">
        <div class="flex-1">
          <p class="text-sm font-medium">おすすめ動画のタイトル2</p>
        </div>
      </div>

    </div>
  </div>
</div>