config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "static_pages#about"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get "static_pages/top"
  get "static_pages/about"
  get "static_pages/terms"
  get "static_pages/privacy_policy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :techniques, only: %i[index] do
    get "autocomplete", on: :collection
    get "search", on: :collection
    get "favorites", on: :member
  end
  namespace :techniques do
    resources :youtube, only: %i[new create show edit update destroy]
    resources :twitter, only: %i[new create show edit update destroy]
  end
  resources :favorites, only: %i[create destroy]
  resources :folders, only: %i[new create show edit update destroy]
  resources :categories, only: %i[index show] do
    member do
      post "follow", to: "follows#create"
      delete "unfollow", to: "follows#destroy"
    end
  end
  get "/youtube/title", to: "youtube_api#title"
end

app/models/technique.rb
class Technique < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :source_type, presence: true
  validates :source_url, presence: true

  belongs_to :user

  enum source_type: { youtube: 1, twitter: 2 }

  has_many :favorites, dependent: :destroy
  has_many :technique_categories, dependent: :destroy
  has_many :categories, through: :technique_categories

  attr_accessor :category_names

  # お気に入り順にソートする
  scope :most_favorites, -> {
    left_joins(:favorites).group(:id).order("count(favorites.id) desc")
  }

  after_save :assign_categories

  after_create_commit :send_notifications_for_followers

  YOUTUBE_ID_REGEX = %r{(?:https://www\.youtube\.com(?:/embed/|/watch\?v=)|https://youtu\.be/)([a-zA-Z0-9_-]{11})}

  def youtube_video_id
    return nil unless youtube? && source_url.present?

    match = source_url.match(YOUTUBE_ID_REGEX)

    match[1] if match
  end

  def x_to_twitter_change_url
    return unless twitter? && source_url.match?(/\Ahttps:\/\/x\.com\//)
    source_url.sub("x.com", "twitter.com")
  end

  def calculate_video_timestamp
    if source_type == "youtube"
      time = video_timestamp.split(":").map(&:to_i)

      case time.length
      when 3
        time[0]*3600 + time[1]*60 + time[2]
      when 2
        time[0]*60 + time[1]
      when 1
        time[0]
      else
        0
      end
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "title" ]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  private

  def assign_categories
    return if category_names.blank?

    old_categories = categories.to_a

    new_categories = category_names.split(",").map do |name|
      Category.find_or_create_by(name: name.strip)
    end

    self.categories = new_categories
    removed_categories = old_categories - new_categories

    removed_categories.each do |category|
      if category.reload.technique_categories.empty?
        category.destroy
      end
    end
  end

  def send_notifications_for_followers
    if categories.any?
      categories.each do |category|
        category.followers.where.not(id: user_id).each do |follower|
          notification = Notification.create!(
            user: follower,
            notifiable: self,
            message: "#{category.name}に新しいテクニック「#{title}」が投稿されました。"
          )
          NotificationMailer.new_technique_notification(follower, self, category).deliver_later
        end
      end
    else
      Rails.logger.warn "Warning: Technique ##{id} has no categories associated after commit. No notifications will be sent."
    end
  end
end

app/controllers/techniques/twitter_controller.rb
class Techniques::TwitterController < ApplicationController
  before_action :authenticate_user!, except: [ :show ]

  def new
    @technique = Technique.new(source_type: "twitter")
  end

  def create
    @technique = current_user.techniques.build(technique_params)
    @technique.source_type = "twitter"
    category_names = params[:technique][:category_names]

    if @technique.save
      if category_names.present?
        categories = category_names.split(",").map(&:strip).uniq
        create_or_update_technique_categories(@technique, categories)
      end
      redirect_to techniques_twitter_path(@technique), success: t("defaults.flash_message.created", item: "Xの#{Technique.model_name.human}")
    else
      flash.now[:error] = t("defaults.flash_message.not_created", item: Technique.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @technique = Technique.find(params[:id])
    recommend_id = Technique.where(source_type: "twitter").where.not(id: @technique.id).pluck(:id).sample(2)
    @recommend_techniques = Technique.where(id: recommend_id)
  end

  def edit
    @technique = current_user.techniques.find(params[:id])
  end

  def update
    @technique = current_user.techniques.find(params[:id])
    category_names = params[:technique][:category_names]

    if @technique.update(technique_params)
      if category_names.present?
        categories = params[:technique][:category_names].split(",").map(&:strip).uniq
        create_or_update_technique_categories(@technique, categories)
      end
      redirect_to techniques_twitter_path(@technique), success: t("defaults.flash_message.updated", item: Technique.model_name.human)
    else
      flash.now[:error] = t("defaults.flash_message.not_updated", item: Technique.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    technique = current_user.techniques.find(params[:id])
    technique.destroy!
    redirect_to techniques_path, success: t("defaults.flash_message.deleted", item: Technique.model_name.human), status: :see_other
  end

  private

  def technique_params
    params.require(:technique).permit(:title, :source_type, :source_url)
  end

  def create_or_update_technique_categories(technique, categories)
    technique.categories.destroy_all
    begin
      categories.each do |category|
        category = Category.find_or_create_by(name: category)
        technique.categories << category
      rescue ActiveRecord::RecordInvalid
        false
      end
    end
  end
end

app/controllers/techniques/youtube_controller.rb
class Techniques::YoutubeController < ApplicationController
  before_action :authenticate_user!, except: [ :show ]

  def new
    @technique = Technique.new(source_type: "youtube")
  end

  def create
    @technique = current_user.techniques.build(technique_params)
    @technique.source_type = "youtube"

    if @technique.save
      redirect_to techniques_youtube_path(@technique), success: t("defaults.flash_message.created", item: "Youtubeの#{Technique.model_name.human}")
    else
      flash.now[:error] = t("defaults.flash_message.not_created", item: Technique.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @technique = Technique.find(params[:id])

    # youtubeAPIを引っ張ってくる
    youtube_service = YoutubeService.new
    @movie_title = youtube_service.get_movie_title(@technique.youtube_video_id)

    # おすすめ動画のためにIDをランダムで引っ張ってくる
    recommend_id = Technique.where(source_type: "youtube").where.not(id: @technique.id).pluck(:id).sample(5)
    @recommend_techniques = Technique.where(id: recommend_id)
  end

  def edit
    @technique = current_user.techniques.find(params[:id])
    @technique.category_names = @technique.categories.pluck(:name).join(",")
  end

  def update
    @technique = current_user.techniques.find(params[:id])

    if @technique.update(technique_params)
      redirect_to techniques_youtube_path(@technique), success: t("defaults.flash_message.updated", item: Technique.model_name.human)
    else
      flash.now[:error] = t("defaults.flash_message.not_updated", item: Technique.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    technique = current_user.techniques.find(params[:id])
    technique.destroy!
    redirect_to techniques_path, success: t("defaults.flash_message.deleted", item: Technique.model_name.human), status: :see_other
  end

  private

  def technique_params
    params.require(:technique).permit(:title, :source_type, :source_url, :video_timestamp, :category_names)
  end
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  def index
    # まとめて記載
    most_favorites_techniques = Technique.most_favorites.includes(:categories)

    if params[:most_favorites]
      @techniques = most_favorites_techniques
    else
      @techniques = Technique.includes(:categories).order(created_at: :desc)
    end

    @swiper_youtube_techniques = most_favorites_techniques.where(source_type: "youtube").limit(5)

    @youtube_techniques = @techniques.where(source_type: "youtube").limit(6)
    @twitter_techniques = @techniques.where(source_type: "twitter").limit(6)

    @beginner_categories  = Category.beginner
    @agents_categories = Category.agents
    @maps_categories = Category.maps
    @others_categories = Category.others
  end

  def search
    @q = Technique.ransack(params[:q])
    @results = @q.result(distinct: true).includes(:categories)
  end

  def favorites
    @favorite_techniques = current_user.favorite_techniques.includes(:categories)
    @folders = current_user.folders.includes(:user)

    @folder = Folder.new
    @my_folders = current_user.folders.includes(:user)

    @followed_categories = current_user.following_categories.all
  end

  def autocomplete
    @techniques = Technique.where("title LIKE ?", "%#{params[:q]}%")

    respond_to do |format|
      format.html { render layout: false }
    end
  end

  private
  def folder_params
    params.require(:folder).permit(:title)
  end
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/views/techniques/twitter/edit.html.erb
<% content_for(:title, t(".title")) %>

<div class="flex min-h-full flex-col lg:flex-row lg:m-6 justify-center md:m-12" data-controller="twitter-preview">

  <%# ======左側：入力フォーム====== %>
  <div class="w-full lg:w-1/2 xl:w-1/3">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <h2 class="mt-10 text-center text-2xl/9 font-bold tracking-tight">Xテクニック編集</h2>
    </div>

    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-md">

      <%= form_with model: @technique, url: techniques_twitter_path(@technique) do |f| %>

        <%= render 'shared/error_message', object: f.object %>
        <%= f.hidden_field :source_type %>

        <div class="field py-2 px-4">
          <%= f.text_field :source_url,
                            autofocus: true,
                            autocomplete: "title",
                            class: "input input-md input-bordered w-full",
                            placeholder: "XのURL",
                            data: {
                              twitter_preview_target: "sourceUrl",
                              action: "input->twitter-preview#update"
                            }
          %>
          <span class="label-text-alt ml-2 text-red-600">※必須（Required field）</span>
        </div>

        <div class="field py-2 px-4">
          <%= f.text_field :title,
                            autofocus: true,
                            autocomplete: "title",
                            class: "input input-md input-bordered w-full",
                            placeholder: "オリジナルタイトル（例：ソーヴァ サンセット リコン）",
                            data: {
                              twitter_preview_target: "titleInput",
                              action: "input->twitter-preview#update"
                            }
          %>
        </div>

        <div class="field py-2 px-4">
          <%= f.text_field :category_names,
                class: "input input-md input-bordered w-full",
                placeholder: "カテゴリー名（コンマ（,）区切りで複数入力可能）",
                data: {
                  twitter_preview_target: "categoryInput",
                  action: "input->twitter-preview#update"
                }
          %>
        </div>

        <div class="actions text-center py-4 px-4">
          <%= f.submit "投稿する！", class: "btn btn-wide" %>
        </div>
      <% end %>
    </div>

  </div>

  <%# ======右側：ブラウザのモックアップ====== %>
  <div class="w-full lg:w-1/2 xl:w-2/3 mt-10 ml-4 lg:mt-0 lg:ml-4 lg:mr-4">

    <div class="items-center m-4">
      <h2 class="text-center text-xl font-bold tracking-tight">プレビュー画面</h2>
      <h2 class="text-center text-lg tracking-tight">（こちらで実際に作成されるページを事前確認できます）</h2>
    </div>

    <div class="mockup-browser border-base-300 border">
      <div class="mockup-browser-toolbar">
        <div class="input border-base-300 border">https://v-tactics.com</div>
      </div>

      <%# モックアップの中身 %>

      <div class="border-base-300 flex flex-col items-center justify-center border-t px-4 py-8 md:px-8">

        <div data-twitter-preview-target="preview" class="w-4/5 rounded-lg bg-gray-200 flex items-center justify-center">
          <span class="text-gray-500">投稿前に投稿が確認できます</span>
        </div>

        <div data-twitter-preview-target="previewTitle" class="mt-4 text-xl font-bold line-clamp-1">タイトル</div>

        <div data-twitter-preview-target="previewCategories" class="mt-4 mb-4 flex flex-wrap gap-2">
        </div>

        <%# ボタン系 %>
        <div class="mt-2 flex flex-wrap gap-3">

          <div class="btn bg-black text-white">Xへ</div>

          <div class="btn">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
              <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
            </svg>
            で共有する
          </div>

          <div class="btn">編集</div>
          <div class="btn">削除</div>

          <div class="btn btn-primary">マイフォルダに保存</div>

          <div class="btn btn-soft btn-warning">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
              <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.56.56 0 0 0-.163-.505L1.71 6.745l4.052-.576a.53.53 0 0 0 .393-.288L8 2.223l1.847 3.658a.53.53 0 0 0 .393.288l4.052.575-2.906 2.77a.56.56 0 0 0-.163.506l.694 3.957-3.686-1.894a.5.5 0 0 0-.461 0z"/>
            </svg>
            <span>お気に入り</span>
          </div>

        </div>

      </div>



    </div>
  </div>
</div>

app/views/techniques/twitter/new.html.erb
<% content_for(:title, t(".title")) %>

<div class="flex min-h-full flex-col lg:flex-row lg:m-6 justify-center md:m-12" data-controller="twitter-preview">

  <%# ======左側：入力フォーム====== %>
  <div class="w-full lg:w-1/2 xl:w-1/3">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <h2 class="mt-10 text-center text-2xl/9 font-bold tracking-tight">Xテクニック登録</h2>
    </div>

    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-md">

      <%= form_with model: @technique, url: techniques_twitter_index_path do |f| %>

        <%= render 'shared/error_message', object: f.object %>
        <%= f.hidden_field :source_type %>

        <div class="field py-2 px-4">
          <%= f.text_field :source_url,
                            autofocus: true,
                            autocomplete: "title",
                            class: "input input-md input-bordered w-full",
                            placeholder: "XのURL",
                            data: {
                              twitter_preview_target: "sourceUrl",
                              action: "input->twitter-preview#update"
                            }
          %>
          <span class="label-text-alt ml-2 text-red-600">※必須（Required field）</span>
        </div>

        <div class="field py-2 px-4">
          <%= f.text_field :title,
                            autofocus: true,
                            autocomplete: "title",
                            class: "input input-md input-bordered w-full",
                            placeholder: "オリジナルタイトル（例：ソーヴァ サンセット リコン）",
                            data: {
                              twitter_preview_target: "titleInput",
                              action: "input->twitter-preview#update"
                            }
          %>
        </div>

        <div class="field py-2 px-4">
          <%= f.text_field :category_names,
                class: "input input-md input-bordered w-full",
                placeholder: "カテゴリー名（コンマ（,）区切りで複数入力可能）",
                data: {
                  twitter_preview_target: "categoryInput",
                  action: "input->twitter-preview#update"
                }
          %>
        </div>

        <div class="actions text-center py-4 px-4">
          <%= f.submit "投稿する！", class: "btn btn-wide" %>
        </div>
      <% end %>
    </div>

  </div>

  <%# ======右側：ブラウザのモックアップ====== %>
  <div class="w-full lg:w-1/2 xl:w-2/3 mt-10 ml-4 lg:mt-0 lg:ml-4 lg:mr-4">

    <div class="items-center m-4">
      <h2 class="text-center text-xl font-bold tracking-tight">プレビュー画面</h2>
      <h2 class="text-center text-lg tracking-tight">（こちらで実際に作成されるページを事前確認できます）</h2>
    </div>

    <div class="mockup-browser border-base-300 border">
      <div class="mockup-browser-toolbar">
        <div class="input border-base-300 border">https://v-tactics.com</div>
      </div>

      <%# モックアップの中身 %>

      <div class="border-base-300 flex flex-col items-center justify-center border-t px-4 py-8 md:px-8">

        <div data-twitter-preview-target="preview" class="w-4/5 rounded-lg bg-gray-200 flex items-center justify-center">
          <span class="text-gray-500">投稿前に投稿が確認できます</span>
        </div>

        <div data-twitter-preview-target="previewTitle" class="mt-4 text-xl font-bold line-clamp-1">タイトル</div>

        <div data-twitter-preview-target="previewCategories" class="mt-4 mb-4 flex flex-wrap gap-2">
        </div>

        <%# ボタン系 %>
        <div class="mt-2 flex flex-wrap gap-3">

          <div class="btn bg-black text-white">Xへ</div>

          <div class="btn">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
              <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
            </svg>
            で共有する
          </div>

          <div class="btn">編集</div>
          <div class="btn">削除</div>

          <div class="btn btn-primary">マイフォルダに保存</div>

          <div class="btn btn-soft btn-warning">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
              <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.56.56 0 0 0-.163-.505L1.71 6.745l4.052-.576a.53.53 0 0 0 .393-.288L8 2.223l1.847 3.658a.53.53 0 0 0 .393.288l4.052.575-2.906 2.77a.56.56 0 0 0-.163.506l.694 3.957-3.686-1.894a.5.5 0 0 0-.461 0z"/>
            </svg>
            <span>お気に入り</span>
          </div>

        </div>

      </div>



    </div>
  </div>
</div>

app/views/techniques/twitter/show.html.erb
<% content_for(:title, t(".title")) %>
<div class="flex flex-col md:flex-row max-w-screen-2xl mx-auto px-4 py-6">

  <div class="w-full md:w-2/3 md:pr-6">
    <blockquote class="twitter-tweet">
      <a data-width="300px" data-height="500px" href="<%= @technique.x_to_twitter_change_url %>"></a>
    </blockquote>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <div class="mt-4 text-xl font-bold"><%= @technique.title %></div>

    <div class="mt-4 mb-4">
    <% @technique.categories.each do |category| %>
      <span class="badge badge-outline badge-primary"><%= category.name %></span>
    <% end %>
    </div>

    <div class="mt-2 flex space-x-3">

      <a href="<%= @technique.source_url %>" class="btn bg-gray-500 text-white" target="_blank" rel="noopener noreferrer">Xへ</a>
      <%= link_to "https://twitter.com/intent/tweet?url=#{request.url}%0a&text=#{CGI.escape("#{@technique.title}")}&hashtags=#{CGI.escape('VTACTICS')}", target: '_blank', rel: "noopener noreferrer" do %>
        <div class="btn">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
            <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
          </svg>
          で共有する
        </div>
      <% end %>

      <% if user_signed_in? && current_user.own?(@technique) %>
        <%= link_to "編集", edit_techniques_twitter_path(@technique), id: "button-edit-#{@technique.id}", class: "btn" %>
        <%= link_to "削除", techniques_twitter_path(@technique), id: "button-destroy-#{@technique.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') }, class: "btn" %>
      <% end %>

      <!-- マイフォルダに保存 ボタン -->
      <div class="tooltip" data-tip="もうすぐ実装予定！">
        <a href="#" class="btn btn-primary">マイフォルダに保存</a>
      </div>

      <%# お気に入りボタン %>
      <div id="<%= dom_id(@technique, :favorite_button) %>">
        <%= render "techniques/favorite_button", technique: @technique %>
      </div>

    </div>
  </div>


  <!-- おすすめツイート -->
  <div class="w-full md:w-1/3 mt-6 md:mt-0">
    <h2 class="text-lg font-semibold mb-4">おすすめポスト</h2>

    <% @recommend_techniques.each do |technique| %>

      <%= link_to technique.title, techniques_twitter_path(technique), class: "text-sm font-medium" %>

      <blockquote class="twitter-tweet">
        <a href="<%= technique.x_to_twitter_change_url %>"></a>
      </blockquote>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

    <% end %>

  </div>
</div>