config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "static_pages#about"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get "static_pages/top"
  get "static_pages/about"
  get "static_pages/terms"
  get "static_pages/privacy_policy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :techniques, only: %i[index] do
    get "autocomplete", on: :collection
    get "search", on: :collection
    get "favorites", on: :member
  end
  namespace :techniques do
    resources :youtube, only: %i[new create show edit update destroy]
    resources :twitter, only: %i[new create show edit update destroy]
  end
  resources :favorites, only: %i[create destroy]
  resources :folders, only: %i[new create show edit update destroy]
  resources :categories, only: %i[index show] do
    member do
      post "follow", to: "follows#create"
      delete "unfollow", to: "follows#destroy"
    end
  end
  get "/youtube/title", to: "youtube_api#title"
end

app/models/category.rb
class Category < ApplicationRecord
  AGENTS = [
    "アストラ",
    "ブリーチ",
    "ブリムストーン",
    "チェンバー",
    "クローヴ",
    "サイファー",
    "デッドロック",
    "フェイド",
    "ゲッコー",
    "ハーバー",
    "アイソ",
    "ジェット",
    "KAY/O",
    "キルジョイ",
    "ネオン",
    "オーメン",
    "フェニックス",
    "レイズ",
    "レイナ",
    "セージ",
    "スカイ",
    "ソーヴァ",
    "ヴァイパー",
    "ヨル"
  ]

  MAPS = [
    "アビス",
    "アセント",
    "バインド",
    "ブリーズ",
    "フラクチャー",
    "ヘイヴン",
    "アイスボックス",
    "ロータス",
    "パール",
    "スプリット",
    "サンセット"
  ]

  BEGINNER = [ "初心者" ]

  has_many :technique_categories, dependent: :destroy
  has_many :techniques, through: :technique_categories
  has_many :follows, dependent: :destroy
  has_many :followers, through: :follows, source: :user

  validates :name, presence: true

  scope :agents, -> { where(name: AGENTS) }
  scope :maps, -> { where(name: MAPS) }
  scope :beginner, -> { where(name: BEGINNER) }
  scope :others, -> { where.not(name: AGENTS + MAPS + BEGINNER) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @techniques = @category.techniques.includes(:categories)

    if params[:most_favorites] == "true"
      @techniques = @techniques.most_favorites
    else
      @techniques = @techniques.order(created_at: :desc)
    end
    @youtube_categories_techniques = @techniques.where(source_type: "youtube")
    @twitter_categories_techniques = @techniques.where(source_type: "twitter")
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_twitter_technique.html.erb
<div class="relative mx-auto max-w-7xl">
  <% if @twitter_categories_techniques.present? %>
    <div class="mx-auto mt-8 grid max-w-lg gap-12 lg:max-w-none lg:grid-cols-3">
      <% @twitter_categories_techniques.each do |technique| %>
        <div class="mb-12 flex flex-col overflow-hidden">
          <%= link_to techniques_twitter_path(technique), data: { turbo_frame: "_top" } do %>

            <%# x %>
            <div class="shrink-0">
              <blockquote class="twitter-tweet">
                <a href="<%= technique.x_to_twitter_change_url || technique.source_url %>"></a>
              </blockquote>
              <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>

            <%# テキスト情報 %>
            <div class="flex flex-1 flex-col justify-between pt-6 pl-6 pr-6">
              <div class="flex-1">
                <div class="mt-2 mb-2">
                  <% technique.categories.each do |category| %>
                    <%= link_to category.name, category_path(category), data: { turbo_frame: "_top" }, class: "badge badge-info" %>
                  <% end %>
                </div>

                <div class="mt-3 block">
                  <h3 class="text-2xl font-semibold leading-none tracking-tighter mb-4">
                    <%= technique.title %>
                  </h3>
                </div>
              </div>

            </div>

            <div class="flex justify-center items-center gap-2 mt-2">
              <%= link_to "詳細画面へ", techniques_twitter_path(technique), data: { turbo_frame: "_top" }, class: "btn btn-primary" %>
              <div id="<%= dom_id(technique, :favorite_button) %>">
                <%= render "techniques/favorite_button", technique: technique %>
              </div>
            </div>

          <% end %>

        </div>
      <% end %>
    </div>

    <% else %>

      <div class="mt-6 flex justify-center">
        <div role="alert" class="alert alert-warning">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-6 w-6 shrink-0 stroke-current"
              fill="none"
              viewBox="0 0 24 24">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          <span>Xのテクニックは投稿されていません</span>
        </div>
      </div>

    <% end %>

  </div>
</div>

app/views/categories/_youtube_technique.html.erb
<div class="relative mx-auto max-w-7xl">
  <% if @youtube_categories_techniques.present? %>
    <div class="mx-auto mt-8 grid max-w-lg gap-12 lg:max-w-none lg:grid-cols-3">
      <% @youtube_categories_techniques.each do |technique| %>
        <div class="mb-12 flex flex-col overflow-hidden">
          <%= link_to techniques_youtube_path(technique), data: { turbo_frame: "_top" } do %>

            <%# youtube %>
            <div class="shrink-0">
              <iframe class="w-full aspect-video"
                      src="https://www.youtube.com/embed/<%= technique.youtube_video_id %>?start=<%= technique.calculate_video_timestamp %>"
                      frameborder="0"
                      allowfullscreen>
              </iframe>
            </div>

            <%# テキスト情報 %>
            <div class="flex flex-1 flex-col justify-between pt-6 pl-6 pr-6">
              <div class="flex-1">
                <div class="flex text-sm">
                  <span>開始地点: <%= technique.video_timestamp %></span>
                </div>

                <div class="mt-2 mb-2">
                  <% technique.categories.each do |category| %>
                    <%= link_to category.name, category_path(category), data: { turbo_frame: "_top" }, class: "badge badge-info" %>
                  <% end %>
                </div>

                <div class="mt-3 block">
                  <h3 class="text-2xl font-semibold leading-none tracking-tighter mb-4">
                    <%= technique.title %>
                  </h3>
                  <%# p class="text-lg font-normal mb-4">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
                    facilis asperiores porro quaerat doloribus, eveniet dolore.
                    Adipisci tempora aut inventore optio animi., tempore
                    temporibus quo laudantium.
                  </p%>
                </div>
              </div>

            </div>

            <div class="flex justify-center items-center gap-2 mt-2">
              <%= link_to "詳細画面へ", techniques_youtube_path(technique), data: { turbo_frame: "_top" }, class: "btn btn-primary" %>
              <div id="<%= dom_id(technique, :favorite_button) %>">
                <%= render "techniques/favorite_button", technique: technique %>
              </div>
            </div>

          <% end %>

        </div>
      <% end %>
    </div>

  <% else %>

    <div class="mt-6 flex justify-center">
      <div role="alert" class="alert alert-warning">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6 shrink-0 stroke-current"
            fill="none"
            viewBox="0 0 24 24">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
        <span>YouTubeのテクニックは投稿されていません</span>
      </div>
    </div>

  <% end %>

  </div>
</div>

app/views/categories/index.html.erb
<div class="text-center">
  <div class="text-6xl font-bold m-8">作成されているカテゴリー一覧</div>
  <div>
    <% @categories.each do |category| %>
      <div class="btn btn-primary m-8 btn-wide sm:btn-sm md:btn-md lg:btn-lg"><%= link_to category.name, category_path(category) %></div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="text-center">
  <div class="text-6xl font-bold m-8">「<%= @category.name %>」に関連するテクニック</div>
  <div class="m-8">
    <% if user_signed_in? %>
      <% if current_user.following_categories.include?(@category) %>
        <div class="btn btn-wide"><%= button_to "フォロー解除", unfollow_category_path(@category), method: :delete, data: { confirm: "本当にフォローを解除しますか？" } %></div>
      <% else %>
        <div class="btn btn-primary btn-wide"><%= button_to "フォローする", follow_category_path(@category), method: :post %></div>
      <% end %>
    <% else %>
      <p>フォロー機能を利用するには<a href="<%= new_user_session_path %>">ログイン</a>してください。</p>
    <% end %>
  </div>
</div>

<%= turbo_frame_tag "youtube_section" do %>

<section>
  <div class="container py-8 mx-auto">
    <div class="border-b border-gray-600 pb-4">
      <h3 class="text-xl text-center font-semibold leading-6">
        Movies
      </h3>
    </div>

    <div class="mt-8 text-center">

      <%# UI切り替えの条件式 %>
      <% new_active = !params[:most_favorites].present? %>
      <% favorites_active = params[:most_favorites].present? %>

      表示順：
      <div class="join">
        <%= link_to "新着順", category_path(@category), class: "join-item btn btn-sm #{'btn-success' if new_active}" %>

        <%= link_to "お気に入り数順", category_path(@category, most_favorites: "true"), class: "join-item btn btn-sm #{'btn-warning' if favorites_active}" %>
      </div>
    </div>

    <%= render "categories/youtube_technique" %>

  </div>
</section>

<% end %>


<%= turbo_frame_tag "twitter_section" do %>

<section>
  <div class="container py-8 mx-auto">
    <div class="border-b border-gray-600 pb-4">
      <h3 class="text-xl text-center font-semibold leading-6">
        Posts
      </h3>
    </div>

    <div class="mt-8 text-center">

      <% new_active = !params[:most_favorites].present? %>
      <% favorites_active = params[:most_favorites].present? %>

      表示順：
      <div class="join">
        <%= link_to "新着順", category_path(@category), class: "join-item btn btn-sm #{'btn-success' if new_active}" %>
        <%= link_to "お気に入り数順", category_path(@category, most_favorites: "true"), class: "join-item btn btn-sm #{'btn-warning' if favorites_active}" %>
      </div>
    </div>

    <%= render "categories/twitter_technique" %>

  </div>
</section>

<% end %>